### ISSUE TITLE
Tunnel to a different host?

### ISSUE THREAD

**Issue by msakrejda** [agebrock/inject-tunnel-ssh#2]
As far as I can tell, `inject-tunnel-ssh` only allows you to tunnel other protocols over ssh to the same target host (as the one hosting the ssh server). Is there a way to use the ssh tunnel to connect to a different host?

**Comment by agebrock** [comment]
Well if i understand you correctly that usecase is not supported and will probably never be. 
However you could fork the project and instead of creating and connecting to a tunnel you create a new connection to your server. 

One of the main advantages of injecr-tunnel-ssh is that the port to tunnel the connection dynamic is, to make that work with a remote host you need some kind of server client application, but yeah like i said that is out of  scope....

I hope i got you right..

**Comment by netputer** [comment]
I think this module can do this.

For example: I want to connect `mongodb.private.com:3456` through SSH `board.public.com:22`. Just configure like this:

```
require('inject-tunnel-ssh')([{
  host: 'board.public.com',
  username: 'player',
  dstHost: 'mongodb.private.com',
  dstPort: 3456
}]).on('error',console.log);
```

And connect to MongoDB with some tricky:

```
mongoose.connect('mongodb://board.public.com:3456/someCollection', {
  user: 'username',
  pass: 'password'
};
```

It works. The reason is in this line:

```
var configElement = find(configCollection, {host: options.host, dstPort: options.port});
```

Maybe we replace `options.host` into `options.dstHost` so that we can connect to `mongodb.private.com` without any weird code. But I don't know if it is a good way.

**Comment by schmod** [comment]
@netputer's suggestion makes sense, and seems like it captures the more common use-case.
